function [] = PupilometryInstScreen(olist,session, sessionName, display,Config)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%% Instruction Screen %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Screen('TextSize', display.windowPtr, 30);
Screen('FillRect', display.windowPtr, Config.bgcolor) % change the background color based on session
stimuluscolor=[0 0 0]; % black font
if session == 2
    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        'This experiment consists of solving', ...
        'arithmetic questions while we are', ...
        'recording your pupil size.', ...
        '(press a key to continue)'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
    Screen('Flip',display.windowPtr);
    WaitSecs(.5); KbStrokeWait(Config.Key);
    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        'The experiment consists of 2 phases.', ...
        'The first part is the Staircase Task.', ...
        'This part takes around 10 minutes.', ...
        'During this part, there will be no pupil recording.', ...
        '(press a key to continue)'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
    Screen('Flip',display.windowPtr);
    WaitSecs(.5); KbStrokeWait(Config.Key);
    
    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        'In this phase you will solve gradually more ', ...
        'difficult arithmetic summation questions.', ...
        'Before every question, there will be a + sign,',...
        'that means look at the + sign and wait for the question.',...
        'When the question comes, solve the problem in your mind,',...
        'as carefully and as quickly as you can.',...
        'Then, enter your response using numeric',...
        'keys on the keyboard. Finally, press ENTER.',...
        'You can use Backspace to delete your response.',...
        'Now, press a key to start.'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
    Screen('Flip',display.windowPtr);
    WaitSecs(.5); KbStrokeWait(Config.Key);
    
elseif session ~= 2
    if olist == 2
        DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
            'There will be 8 blocks total and each block', ...
            'will last a total of 4 minutes. ', ...
            'In the beginning of each block, we will', ...
            'calibrate the pupil recording device.', ...
            '(press a key to continue)'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
        Screen('Flip',display.windowPtr);
        WaitSecs(.5); KbStrokeWait(Config.Key);
        
        
        DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
            'In this part, each problem type will', ...
            'be cued with a unique letter:',...
            '"P", "A", "Y", "Q"', ...
            'to let you know what type of problem', ...
            'to expect to solve in each block.', ...
            'Press a key to continue.'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
        Screen('Flip',display.windowPtr);
        WaitSecs(.5); KbStrokeWait(Config.Key);
        
        
        DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
            'So, when you see a letter on the screen, you will', ...
            'know what type of summation the upcoming problem', ...
            'will be and that you should get ready to solve it.', ...
            '(press a key to continue)'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
        Screen('Flip',display.windowPtr);
        WaitSecs(.5); KbStrokeWait(Config.Key);
        
        DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
            'Before and following the letter presentations,', ...
            'there will be the + signs as before. The duration', ...
            'of the + signs will vary. Importantly, make sure to', ...
            ' look at the + sign when it is on.', ...
            '(press a key to continue)'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
        Screen('Flip',display.windowPtr);
        WaitSecs(.5); KbStrokeWait(Config.Key);
        
        
        DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
            'During these blocks, we will be measuring your pupil ', ...
            'size. So, try not to blink too much if you can.', ...
            'But you can blink as much as you need when you', ...
            'are viewing the numbers and solving the problems.',...
            '(press a key to continue)'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
        Screen('Flip',display.windowPtr);
        WaitSecs(.5); KbStrokeWait(Config.Key);
        
        DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
            'If you have question, please ask now.', ...
            'Otherwise, you can press a key to start.'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
        Screen('Flip',display.windowPtr);
        WaitSecs(.5); KbStrokeWait(Config.Key);
        
    end
    
    DrawFormattedText(display.windowPtr, ['The upcoming task name is "' sessionName '"'], 'center', 'center', stimuluscolor, [100]);
    Screen('Flip',display.windowPtr);
    WaitSecs(.5); WaitSecs(Config.ITImean);
    
    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        'Before you start,',...
        'take a short break.', ...
        'When you are ready,', ...
        'press a key to continue.'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
    Screen('Flip',display.windowPtr);
    WaitSecs(.5); KbStrokeWait(Config.Key);
    
    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        'Get ready for pupil calibration!',...
        'When you see the dot, follow the dot with your eyes.', ...
        'Make sure to fixate on the dot and NOT blink.', ...
        'Now press a key to calibrate.'), 'center', 'center', stimuluscolor, [100],[],[],[1.25]);
    Screen('Flip',display.windowPtr);
    KbStrokeWait(Config.Key);
end


Screen('FillRect', display.windowPtr, Config.bgcolor, [10 0 20 10])
Screen('Flip',display.windowPtr);
WaitSecs(Config.ITImean);
end